version: '2.2'
services:
    rabbitmq:
        image: orangehrm/orangehrm-rabbitmq:rabbitmq-3.9.8-centos-7
        container_name: rabbitmq_container
        volumes:
        - ./config/certs:/cert_rabbitmq/
        - ./config/conf:/etc/rabbitmq
        - rabbitmq:/var/lib/rabbitmq
        restart: always
        hostname: rabbitmq-server
volumes:
    rabbitmq: